---
- name: Package install
  ansible.builtin.dnf:
    name:
      - httpd-{{ httpd_version }}
      - mod_ssl-{{ httpd_version }}
    state: present

- name: Stop httpd service
  ansible.builtin.service:
    name: httpd
    state: stopped

- name: Replace "Listen 80" with "Listen 0.0.0.0:80"
  ansible.builtin.replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen\s+80$'
    replace: 'Listen 0.0.0.0:80'

- name: Templating httpd conf file
  ansible.builtin.template:
    src: "httpd.conf.j2"
    dest: /etc/httpd/conf.d/{{ this_name }}.conf
    mode: "0664"

- name: Crt file
  ansible.builtin.copy:
    src: ssl/httpd.crt
    dest: "{{ httpd_ssl_cert_file }}"
    mode: "0664"

- name: Key file
  ansible.builtin.copy:
    src: ssl/httpd.key
    dest: "{{ httpd_ssl_key_file }}"
    mode: "0400"

- name: Copy HTML file
  ansible.builtin.copy:
    src: "{{ this_game }}.html"
    dest: /var/www/html/index.html
    mode: "0664"

- name: Start service
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true
